/**
 * מיפוי סטטי של 245 עמודות ספר תורה (יריעות 1,61,62 → 3 עמודות; כל השאר → 4).
 * נוצר מייבוא CSV: חלוקת_עמודים_רמה11.csv (מספר עמוד = אינדקס גליל; עמודה ביריעה = סדר בתוך היריעה).
 */

export type TorahColumnMapping = {
  sheet: number;
  column: number;
  parsha: string;
  firstWord: string;
  lastWord: string;
};

export const TORAH_COLUMNS = [
  { sheet: 1, column: 1, parsha: "בראשית", firstWord: "בראשית", lastWord: "למינה" },
  { sheet: 1, column: 2, parsha: "בראשית", firstWord: "ואת", lastWord: "תמות" },
  { sheet: 1, column: 3, parsha: "בראשית", firstWord: "ויאמר", lastWord: "תשוקתך" },
  { sheet: 2, column: 1, parsha: "נח", firstWord: "והוא", lastWord: "מתושאל" },
  { sheet: 2, column: 2, parsha: "נח", firstWord: "ומתושאל", lastWord: "שנה" },
  { sheet: 2, column: 3, parsha: "נח", firstWord: "ויולד", lastWord: "רחבה" },
  { sheet: 2, column: 4, parsha: "נח", firstWord: "ושלשים", lastWord: "הארץ" },
  { sheet: 3, column: 1, parsha: "נח", firstWord: "ותלך", lastWord: "במזבח" },
  { sheet: 3, column: 2, parsha: "נח", firstWord: "וירח", lastWord: "הקטן" },
  { sheet: 3, column: 3, parsha: "נח", firstWord: "ויאמר", lastWord: "המבול" },
  { sheet: 3, column: 4, parsha: "נח", firstWord: "ויהי", lastWord: "לוט" },
  { sheet: 4, column: 1, parsha: "לך לך", firstWord: "וימת", lastWord: "לו" },
  { sheet: 4, column: 2, parsha: "לך לך", firstWord: "ויעל", lastWord: "תמר" },
  { sheet: 4, column: 3, parsha: "לך לך", firstWord: "ויצא", lastWord: "אירשנה" },
  { sheet: 4, column: 4, parsha: "לך לך", firstWord: "ויאמר", lastWord: "קדש" },
  { sheet: 5, column: 1, parsha: "וירא", firstWord: "ובין", lastWord: "אברהם" },
  { sheet: 5, column: 2, parsha: "וירא", firstWord: "וימל", lastWord: "אברהם" },
  { sheet: 5, column: 3, parsha: "וירא", firstWord: "ויאמר", lastWord: "ובנתיך" },
  { sheet: 5, column: 4, parsha: "וירא", firstWord: "וכל", lastWord: "הצעירה" },
  { sheet: 6, column: 1, parsha: "חיי שרה", firstWord: "ותשכב", lastWord: "יצחק" },
  { sheet: 6, column: 2, parsha: "חיי שרה", firstWord: "וימל", lastWord: "לבדנה" },
  { sheet: 6, column: 3, parsha: "חיי שרה", firstWord: "ויאמר", lastWord: "נעריו" },
  { sheet: 6, column: 4, parsha: "חיי שרה", firstWord: "ויקמו", lastWord: "השדה" },
  { sheet: 7, column: 1, parsha: "תולדות", firstWord: "והמערה", lastWord: "ללין" },
  { sheet: 7, column: 2, parsha: "תולדות", firstWord: "ותאמר", lastWord: "לי" },
  { sheet: 7, column: 3, parsha: "תולדות", firstWord: "ואם", lastWord: "אשתו" },
  { sheet: 7, column: 4, parsha: "תולדות", firstWord: "ויהי", lastWord: "לך" },
  { sheet: 8, column: 1, parsha: "ויצא", firstWord: "ולזרעך", lastWord: "עמך" },
  { sheet: 8, column: 2, parsha: "ויצא", firstWord: "ונאמר", lastWord: "נא" },
  { sheet: 8, column: 3, parsha: "ויצא", firstWord: "ואמשך", lastWord: "אחד" },
  { sheet: 8, column: 4, parsha: "ויצא", firstWord: "ותאמר", lastWord: "וירא" },
  { sheet: 9, column: 1, parsha: "ויצא", firstWord: "ואתנה", lastWord: "מלאה" },
  { sheet: 9, column: 2, parsha: "ויצא", firstWord: "ותקרא", lastWord: "חרפתי" },
  { sheet: 9, column: 3, parsha: "ויצא", firstWord: "ויעבד", lastWord: "עמדי" },
  { sheet: 9, column: 4, parsha: "ויצא", firstWord: "והנה", lastWord: "עמדי" },
  { sheet: 10, column: 1, parsha: "וישלח", firstWord: "וירא", lastWord: "זה" },
  { sheet: 10, column: 2, parsha: "וישלח", firstWord: "ויאמר", lastWord: "יעקב" },
  { sheet: 10, column: 3, parsha: "וישלח", firstWord: "ויקרא", lastWord: "הארץ" },
  { sheet: 10, column: 4, parsha: "וישלח", firstWord: "וקח", lastWord: "חמריהם" },
  { sheet: 11, column: 1, parsha: "וישב", firstWord: "ואת", lastWord: "אביו" },
  { sheet: 11, column: 2, parsha: "וישב", firstWord: "וישמע", lastWord: "ואצר" },
  { sheet: 11, column: 3, parsha: "וישב", firstWord: "ודישן", lastWord: "דבריו" },
  { sheet: 11, column: 4, parsha: "וישב", firstWord: "ויחלם", lastWord: "שמלתיו" },
  { sheet: 12, column: 1, parsha: "מקץ", firstWord: "וישם", lastWord: "כלתך" },
  { sheet: 12, column: 2, parsha: "מקץ", firstWord: "וגם", lastWord: "החוצה" },
  { sheet: 12, column: 3, parsha: "מקץ", firstWord: "ויהי", lastWord: "מעליך" },
  { sheet: 12, column: 4, parsha: "מקץ", firstWord: "ותלה", lastWord: "הבריאת" },
  { sheet: 13, column: 1, parsha: "מקץ", firstWord: "ותבאנה", lastWord: "לאשה" },
  { sheet: 13, column: 2, parsha: "מקץ", firstWord: "ויצא", lastWord: "איננו" },
  { sheet: 13, column: 3, parsha: "מקץ", firstWord: "ויאמר", lastWord: "אליך" },
  { sheet: 13, column: 4, parsha: "מקץ", firstWord: "ויאמר", lastWord: "בידנו" },
  { sheet: 14, column: 1, parsha: "ויגש", firstWord: "וכסף", lastWord: "החל" },
  { sheet: 14, column: 2, parsha: "ויגש", firstWord: "ובקטן", lastWord: "אלי" },
  { sheet: 14, column: 3, parsha: "ויגש", firstWord: "ויגשו", lastWord: "אמות" },
  { sheet: 14, column: 4, parsha: "ויגש", firstWord: "ויסע", lastWord: "עוד" },
  { sheet: 15, column: 1, parsha: "ויחי", firstWord: "ויאמר", lastWord: "השנית" },
  { sheet: 15, column: 2, parsha: "ויחי", firstWord: "ויאמרו", lastWord: "אפרתה" },
  { sheet: 15, column: 3, parsha: "ויחי", firstWord: "ואקברה", lastWord: "בישראל" },
  { sheet: 15, column: 4, parsha: "ויחי", firstWord: "יהודה", lastWord: "ישראל" },
  { sheet: 16, column: 1, parsha: "שמות", firstWord: "וימלאו", lastWord: "מאה" },
  { sheet: 16, column: 2, parsha: "שמות", firstWord: "ועשר", lastWord: "היאר" },
  { sheet: 16, column: 3, parsha: "שמות", firstWord: "ונערתיה", lastWord: "הסנה" },
  { sheet: 16, column: 4, parsha: "שמות", firstWord: "ויאמר", lastWord: "ויאמר" },
  { sheet: 17, column: 1, parsha: "וארא", firstWord: "והן", lastWord: "במלון" },
  { sheet: 17, column: 2, parsha: "וארא", firstWord: "ויפגשהו", lastWord: "תתנו" },
  { sheet: 17, column: 3, parsha: "וארא", firstWord: "ויראו", lastWord: "מחלי" },
  { sheet: 17, column: 4, parsha: "וארא", firstWord: "ומושי", lastWord: "המימה" },
  { sheet: 18, column: 1, parsha: "בא", firstWord: "ונצבת", lastWord: "פרעה" },
  { sheet: 18, column: 2, parsha: "בא", firstWord: "ויצעק", lastWord: "עמי" },
  { sheet: 18, column: 3, parsha: "בא", firstWord: "ויעבדני", lastWord: "וברד" },
  { sheet: 18, column: 4, parsha: "בא", firstWord: "ותהלך", lastWord: "בצאננו" },
  { sheet: 19, column: 1, parsha: "בא", firstWord: "ובבקרנו", lastWord: "העם" },
  { sheet: 19, column: 2, parsha: "בא", firstWord: "וישאלו", lastWord: "עלכם" },
  { sheet: 19, column: 3, parsha: "בא", firstWord: "ולא", lastWord: "אתי" },
  { sheet: 19, column: 4, parsha: "בא", firstWord: "ותחזק", lastWord: "גבלך" },
  { sheet: 20, column: 1, parsha: "בשלח", firstWord: "והגדת", lastWord: "מצרים" },
  { sheet: 20, column: 2, parsha: "בשלח", firstWord: "וירדף", lastWord: "פרעה" },
  { sheet: 20, column: 3, parsha: "שירת הים", firstWord: "הבאים", lastWord: "מרה" },
  { sheet: 20, column: 4, parsha: "בשלח", firstWord: "וילנו", lastWord: "תקחו" },
  { sheet: 21, column: 1, parsha: "יתרו", firstWord: "ויעשו", lastWord: "וסקלני" },
  { sheet: 21, column: 2, parsha: "יתרו", firstWord: "ויאמר", lastWord: "עליהם" },
  { sheet: 21, column: 3, parsha: "יתרו", firstWord: "ויקח", lastWord: "משה" },
  { sheet: 21, column: 4, parsha: "יתרו", firstWord: "ויקרא", lastWord: "לאהבי" },
  { sheet: 22, column: 1, parsha: "משפטים", firstWord: "ולשמרי", lastWord: "חפשי" },
  { sheet: 22, column: 2, parsha: "משפטים", firstWord: "והגישו", lastWord: "לבעליו" },
  { sheet: 22, column: 3, parsha: "משפטים", firstWord: "והמת", lastWord: "אלמנות" },
  { sheet: 22, column: 4, parsha: "משפטים", firstWord: "ובניכם", lastWord: "מפניו" },
  { sheet: 23, column: 1, parsha: "תרומה", firstWord: "ושמע", lastWord: "האבן" },
  { sheet: 23, column: 2, parsha: "תרומה", firstWord: "והתורה", lastWord: "טהור" },
  { sheet: 23, column: 3, parsha: "תרומה", firstWord: "ועשית", lastWord: "לבד" },
  { sheet: 23, column: 4, parsha: "תרומה", firstWord: "ואת", lastWord: "הקדש" },
  { sheet: 24, column: 1, parsha: "תצוה", firstWord: "ובין", lastWord: "אהרן" },
  { sheet: 24, column: 2, parsha: "תצוה", firstWord: "ובניו", lastWord: "החשן" },
  { sheet: 24, column: 3, parsha: "תצוה", firstWord: "ואת", lastWord: "האילם" },
  { sheet: 24, column: 4, parsha: "תצוה", firstWord: "ואת", lastWord: "לאהרן" },
  { sheet: 25, column: 1, parsha: "כי תשא", firstWord: "ומאשר", lastWord: "שמה" },
  { sheet: 25, column: 2, parsha: "כי תשא", firstWord: "והקטיר", lastWord: "זר" },
  { sheet: 25, column: 3, parsha: "כי תשא", firstWord: "ונכרת", lastWord: "לו" },
  { sheet: 25, column: 4, parsha: "כי תשא", firstWord: "ויאמר", lastWord: "לו" },
  { sheet: 26, column: 1, parsha: "ויקהל", firstWord: "ואמר", lastWord: "רעהו" },
  { sheet: 26, column: 2, parsha: "ויקהל", firstWord: "ושב", lastWord: "עמך" },
  { sheet: 26, column: 3, parsha: "ויקהל", firstWord: "שמר", lastWord: "משה" },
  { sheet: 26, column: 4, parsha: "ויקהל", firstWord: "והשיב", lastWord: "העזים" },
  { sheet: 27, column: 1, parsha: "ויקהל", firstWord: "והנשאם", lastWord: "האחת" },
  { sheet: 27, column: 2, parsha: "ויקהל", firstWord: "וחמשים", lastWord: "וארגמן" },
  { sheet: 27, column: 3, parsha: "ויקהל", firstWord: "ותולעת", lastWord: "ומלקחיה" },
  { sheet: 27, column: 4, parsha: "ויקהל", firstWord: "ומחתתיה", lastWord: "ארבעה" },
  { sheet: 28, column: 1, parsha: "פקודי/ויקרא", firstWord: "ואדניהם", lastWord: "משה" },
  { sheet: 28, column: 2, parsha: "פקודי/ויקרא", firstWord: "ויעש", lastWord: "עשו" },
  { sheet: 28, column: 3, parsha: "פקודי/ויקרא", firstWord: "ויביאו", lastWord: "אדניו" },
  { sheet: 28, column: 4, parsha: "פקודי/ויקרא", firstWord: "וישם", lastWord: "הבקר" },
  { sheet: 29, column: 1, parsha: "ויקרא", firstWord: "ומן", lastWord: "תעשה" },
  { sheet: 29, column: 2, parsha: "ויקרא", firstWord: "והבאת", lastWord: "הקרב" },
  { sheet: 29, column: 3, parsha: "ויקרא", firstWord: "ואת", lastWord: "לו" },
  { sheet: 29, column: 4, parsha: "ויקרא", firstWord: "וכפר", lastWord: "עליה" },
  { sheet: 30, column: 1, parsha: "צו", firstWord: "והביא", lastWord: "הכהן" },
  { sheet: 30, column: 2, parsha: "צו", firstWord: "וכפר", lastWord: "תשרף" },
  { sheet: 30, column: 3, parsha: "צו", firstWord: "וזאת", lastWord: "לעוף" },
  { sheet: 30, column: 4, parsha: "צו", firstWord: "ולבהמה", lastWord: "החטאת" },
  { sheet: 31, column: 1, parsha: "שמיני", firstWord: "ויסמך", lastWord: "עליכם" },
  { sheet: 31, column: 2, parsha: "שמיני", firstWord: "ופתח", lastWord: "העם" },
  { sheet: 31, column: 3, parsha: "שמיני", firstWord: "ותצא", lastWord: "חטאתם" },
  { sheet: 31, column: 4, parsha: "שמיני", firstWord: "ואת", lastWord: "הערב" },
  { sheet: 32, column: 1, parsha: "תזריע/מצורע", firstWord: "והנשא", lastWord: "יום" },
  { sheet: 32, column: 2, parsha: "תזריע/מצורע", firstWord: "וששת", lastWord: "אדמדמת" },
  { sheet: 32, column: 3, parsha: "תזריע/מצורע", firstWord: "ונראה", lastWord: "הוא" },
  { sheet: 32, column: 4, parsha: "תזריע/מצורע", firstWord: "וכי", lastWord: "ואזב" },
  { sheet: 33, column: 1, parsha: "אחרי מות", firstWord: "וצוה", lastWord: "האשם" },
  { sheet: 33, column: 2, parsha: "אחרי מות", firstWord: "ואשה", lastWord: "הנגע" },
  { sheet: 33, column: 3, parsha: "אחרי מות", firstWord: "ולקח", lastWord: "הערב" },
  { sheet: 33, column: 4, parsha: "אחרי מות", firstWord: "ולקח", lastWord: "על" },
  { sheet: 34, column: 1, parsha: "קדושים", firstWord: "ואשה", lastWord: "ערתם" },
  { sheet: 34, column: 2, parsha: "קדושים", firstWord: "שני", lastWord: "דמו" },
  { sheet: 34, column: 3, parsha: "קדושים", firstWord: "ואת", lastWord: "בה" },
  { sheet: 34, column: 4, parsha: "קדושים", firstWord: "וכסהו", lastWord: "זרע" },
  { sheet: 35, column: 1, parsha: "אמור", firstWord: "והוא", lastWord: "אחד" },
  { sheet: 35, column: 2, parsha: "אמור", firstWord: "והוא", lastWord: "אהרן" },
  { sheet: 35, column: 3, parsha: "אמור", firstWord: "ועשיתם", lastWord: "ולבנו" },
  { sheet: 35, column: 4, parsha: "אמור", firstWord: "ולבתו", lastWord: "חקתי" },
  { sheet: 36, column: 1, parsha: "בהר", firstWord: "וכי", lastWord: "שלמים" },
  { sheet: 36, column: 2, parsha: "בהר", firstWord: "והניף", lastWord: "ימים" },
  { sheet: 36, column: 3, parsha: "בהר", firstWord: "וחגתם", lastWord: "למחנה" },
  { sheet: 36, column: 4, parsha: "בהר", firstWord: "וירגמו", lastWord: "גרים" },
  { sheet: 37, column: 1, parsha: "בחקתי", firstWord: "ותושבים", lastWord: "גר" },
  { sheet: 37, column: 2, parsha: "בחקתי", firstWord: "ותושב", lastWord: "אתכם" },
  { sheet: 37, column: 3, parsha: "בחקתי", firstWord: "ואם", lastWord: "יען" },
  { sheet: 37, column: 4, parsha: "בחקתי", firstWord: "וביען", lastWord: "עוד" },
  { sheet: 38, column: 1, parsha: "במדבר", firstWord: "והיה", lastWord: "הם" },
  { sheet: 38, column: 2, parsha: "במדבר", firstWord: "ויקח", lastWord: "אלף" },
  { sheet: 38, column: 3, parsha: "במדבר", firstWord: "וארבע", lastWord: "וצבאו" },
  { sheet: 38, column: 4, parsha: "במדבר", firstWord: "ופקדיו", lastWord: "אבתיו" },
  { sheet: 39, column: 1, parsha: "נשא", firstWord: "ואלה", lastWord: "אלפים" },
  { sheet: 39, column: 2, parsha: "נשא", firstWord: "ושש", lastWord: "משה" },
  { sheet: 39, column: 3, parsha: "נשא", firstWord: "וידבר", lastWord: "לעבד" },
  { sheet: 39, column: 4, parsha: "נשא", firstWord: "ולמשא", lastWord: "שנה" },
  { sheet: 40, column: 1, parsha: "נשא", firstWord: "ומעלה", lastWord: "לאשם" },
  { sheet: 40, column: 2, parsha: "נשא", firstWord: "ואת", lastWord: "ישאו" },
  { sheet: 40, column: 3, parsha: "נשא", firstWord: "והימים", lastWord: "לחטאת" },
  { sheet: 40, column: 4, parsha: "נשא", firstWord: "ויקריבו", lastWord: "האלה" },
  { sheet: 41, column: 1, parsha: "בהעלתך", firstWord: "ולזבח", lastWord: "שלשים" },
  { sheet: 41, column: 2, parsha: "בהעלתך", firstWord: "ומאה", lastWord: "אלפים" },
  { sheet: 41, column: 3, parsha: "בהעלתך", firstWord: "וארבע", lastWord: "לאהרן" },
  { sheet: 41, column: 4, parsha: "בהעלתך", firstWord: "ולבניו", lastWord: "גר" },
  { sheet: 42, column: 1, parsha: "בהעלתך", firstWord: "ועשה", lastWord: "לצבאתם" },
  { sheet: 42, column: 2, parsha: "בהעלתך", firstWord: "ועל", lastWord: "בפרור" },
  { sheet: 42, column: 3, parsha: "בהעלתך", firstWord: "ועשו", lastWord: "למשה" },
  { sheet: 42, column: 4, parsha: "בהעלתך", firstWord: "ויאמר", lastWord: "פארן" },
  { sheet: 43, column: 1, parsha: "שלח", firstWord: "וידבר", lastWord: "לה" },
  { sheet: 43, column: 2, parsha: "שלח", firstWord: "והאנשים", lastWord: "הנה" },
  { sheet: 43, column: 3, parsha: "שלח", firstWord: "ויאמר", lastWord: "המחנה" },
  { sheet: 43, column: 4, parsha: "שלח", firstWord: "וירד", lastWord: "שגגתם" },
  { sheet: 44, column: 1, parsha: "קרח", firstWord: "ונסלח", lastWord: "מחר" },
  { sheet: 44, column: 2, parsha: "קרח", firstWord: "והיה", lastWord: "שאלה" },
  { sheet: 44, column: 3, parsha: "קרח", firstWord: "וידעתם", lastWord: "אבתם" },
  { sheet: 44, column: 4, parsha: "קרח", firstWord: "והנחתם", lastWord: "לך" },
  { sheet: 45, column: 1, parsha: "חקת", firstWord: "וזה", lastWord: "אתם" },
  { sheet: 45, column: 2, parsha: "חקת", firstWord: "וביתכם", lastWord: "יתחטא" },
  { sheet: 45, column: 3, parsha: "חקת", firstWord: "ונכרתה", lastWord: "נעלה" },
  { sheet: 45, column: 4, parsha: "חקת", firstWord: "ואם", lastWord: "מואב" },
  { sheet: 46, column: 1, parsha: "בלק", firstWord: "ובין", lastWord: "השדה" },
  { sheet: 46, column: 2, parsha: "בלק", firstWord: "ובלק", lastWord: "עבור" },
  { sheet: 46, column: 3, parsha: "בלק", firstWord: "ויעמד", lastWord: "יעקב" },
  { sheet: 46, column: 4, parsha: "בלק", firstWord: "ולכה", lastWord: "עינים" },
  { sheet: 47, column: 1, parsha: "פינחס", firstWord: "מה", lastWord: "הכהן" },
  { sheet: 47, column: 2, parsha: "פינחס", firstWord: "ויקם", lastWord: "אלף" },
  { sheet: 47, column: 3, parsha: "פינחס", firstWord: "ומאתים", lastWord: "אלף" },
  { sheet: 47, column: 4, parsha: "פינחס", firstWord: "ושש", lastWord: "יפנה" },
  { sheet: 48, column: 1, parsha: "מטות", firstWord: "ויהושע", lastWord: "משה" },
  { sheet: 48, column: 2, parsha: "מטות", firstWord: "וידבר", lastWord: "תעשו" },
  { sheet: 48, column: 3, parsha: "מטות", firstWord: "והקרבתם", lastWord: "התמיד" },
  { sheet: 48, column: 4, parsha: "מטות", firstWord: "ומנחתה", lastWord: "נדריה" },
  { sheet: 49, column: 1, parsha: "מטות", firstWord: "ואסריה", lastWord: "משה" },
  { sheet: 49, column: 2, parsha: "מטות", firstWord: "ואלעזר", lastWord: "מאות" },
  { sheet: 49, column: 3, parsha: "מטות", firstWord: "ומכסם", lastWord: "ההוא" },
  { sheet: 49, column: 4, parsha: "מטות", firstWord: "וישבע", lastWord: "האמרי" },
  { sheet: 50, column: 1, parsha: "מסעי", firstWord: "ואת", lastWord: "בחשמנה" },
  { sheet: 50, column: 2, parsha: "מסעי", firstWord: "ויסעו", lastWord: "אדר" },
  { sheet: 50, column: 3, parsha: "מסעי", firstWord: "ועבר", lastWord: "הערים" },
  { sheet: 50, column: 4, parsha: "מסעי", firstWord: "ואת", lastWord: "יומת" },
  { sheet: 51, column: 1, parsha: "דברים", firstWord: "ולא", lastWord: "ברנע" },
  { sheet: 51, column: 2, parsha: "דברים", firstWord: "ויהי", lastWord: "אשכל" },
  { sheet: 51, column: 3, parsha: "דברים", firstWord: "וירגלו", lastWord: "צפנה" },
  { sheet: 51, column: 4, parsha: "דברים", firstWord: "ואת", lastWord: "מפניך" },
  { sheet: 52, column: 1, parsha: "ואתחנן", firstWord: "ואשלח", lastWord: "איש" },
  { sheet: 52, column: 2, parsha: "ואתחנן", firstWord: "ואת", lastWord: "אתכם" },
  { sheet: 52, column: 3, parsha: "ואתחנן", firstWord: "ולא", lastWord: "הירדן" },
  { sheet: 52, column: 4, parsha: "ואתחנן", firstWord: "ולבלתי", lastWord: "אחריך" },
  { sheet: 53, column: 1, parsha: "עקב", firstWord: "ולמען", lastWord: "וחמרך" },
  { sheet: 53, column: 2, parsha: "עקב", firstWord: "וכל", lastWord: "חקתיו" },
  { sheet: 53, column: 3, parsha: "עקב", firstWord: "ומצותיו", lastWord: "לרשתה" },
  { sheet: 53, column: 4, parsha: "עקב", firstWord: "ונשל", lastWord: "הנשארים" },
  { sheet: 54, column: 1, parsha: "ראה", firstWord: "והנסתרים", lastWord: "באחריתך" },
  { sheet: 54, column: 2, parsha: "ראה", firstWord: "ואמרת", lastWord: "השמים" },
  { sheet: 54, column: 3, parsha: "ראה", firstWord: "ואעשה", lastWord: "עשיתי" },
  { sheet: 54, column: 4, parsha: "ראה", firstWord: "ויהיו", lastWord: "לדתן" },
  { sheet: 55, column: 1, parsha: "ראה", firstWord: "ולאבירם", lastWord: "פחדכם" },
  { sheet: 55, column: 2, parsha: "ראה", firstWord: "ומוראכם", lastWord: "אתם" },
  { sheet: 55, column: 3, parsha: "ראה", firstWord: "ובניכם", lastWord: "בניהם" },
  { sheet: 55, column: 4, parsha: "ראה", firstWord: "ואת", lastWord: "רחמים" },
  { sheet: 56, column: 1, parsha: "שופטים", firstWord: "ורחמך", lastWord: "בבקר" },
  { sheet: 56, column: 2, parsha: "שופטים", firstWord: "ובצאן", lastWord: "ובדלת" },
  { sheet: 56, column: 3, parsha: "שופטים", firstWord: "והיה", lastWord: "והיתום" },
  { sheet: 56, column: 4, parsha: "שופטים", firstWord: "והאלמנה", lastWord: "ושמאל" },
  { sheet: 57, column: 1, parsha: "כי תצא", firstWord: "והאיש", lastWord: "מעננים" },
  { sheet: 57, column: 2, parsha: "כי תצא", firstWord: "ואל", lastWord: "האל" },
  { sheet: 57, column: 3, parsha: "כי תצא", firstWord: "ושלחו", lastWord: "לך" },
  { sheet: 57, column: 4, parsha: "כי תצא", firstWord: "ואכלת", lastWord: "שנואה" },
  { sheet: 58, column: 1, parsha: "כי תצא", firstWord: "וילדו", lastWord: "דברים" },
  { sheet: 58, column: 2, parsha: "כי תצא", firstWord: "וכתב", lastWord: "ממצרים" },
  { sheet: 58, column: 3, parsha: "כי תצא", firstWord: "ואשר", lastWord: "האחרון" },
  { sheet: 58, column: 4, parsha: "כי תצא", firstWord: "והוצא", lastWord: "אנשים" },
  { sheet: 59, column: 1, parsha: "כי תבוא", firstWord: "וברוך", lastWord: "לנו" },
  { sheet: 59, column: 2, parsha: "כי תבוא", firstWord: "ונגשו", lastWord: "חלב" },
  { sheet: 59, column: 3, parsha: "כי תבוא", firstWord: "ולקח", lastWord: "בעיר" },
  { sheet: 59, column: 4, parsha: "כי תבוא", firstWord: "ודבש", lastWord: "הארץ" },
  { sheet: 60, column: 1, parsha: "נצבים", firstWord: "וראו", lastWord: "אתך" },
  { sheet: 60, column: 2, parsha: "נצבים", firstWord: "ואין", lastWord: "בחרב" },
  { sheet: 60, column: 3, parsha: "נצבים", firstWord: "והצר", lastWord: "רחוקה" },
  { sheet: 60, column: 4, parsha: "נצבים", firstWord: "ויקרא", lastWord: "לנו" },
  { sheet: 61, column: 1, parsha: "וילך", firstWord: "וישמענו", lastWord: "האנשים" },
  { sheet: 61, column: 2, parsha: "וילך", firstWord: "והנשים", lastWord: "האלה" },
  { sheet: 61, column: 3, parsha: "האזינו א'", firstWord: "ואעידה", lastWord: "באפי" },
  { sheet: 62, column: 1, parsha: "האזינו ב'", firstWord: "ותיקד", lastWord: "חייכם" },
  { sheet: 62, column: 2, parsha: "וזאת הברכה", firstWord: "ובדבר", lastWord: "אפרים" },
  { sheet: 62, column: 3, parsha: "וזאת הברכה", firstWord: "והם", lastWord: "ישראל" }
] as const satisfies readonly TorahColumnMapping[];

export const TORAH_COLUMN_COUNT = TORAH_COLUMNS.length;

/** כל העמודות ביריעה נתונה (לפי מספר יריעה 1–62) */
export function getTorahColumnsForSheet(sheetNumber: number): TorahColumnMapping[] {
  return TORAH_COLUMNS.filter((c) => c.sheet === sheetNumber);
}

/** פרשות ייחודיות ביריעה (לתצוגה קצרה) */
export function uniqueParshiyotOnSheet(sheetNumber: number): string[] {
  const seen = new Set<string>();
  const list: string[] = [];
  for (const c of getTorahColumnsForSheet(sheetNumber)) {
    const p = c.parsha.trim();
    if (p && p !== "—" && !seen.has(p)) {
      seen.add(p);
      list.push(p);
    }
  }
  return list;
}
